config/routes.rb
Rails.application.routes.draw do

    root 'home#home'
      get 'articles/new' => 'articles#new'
      get 'articles' => 'articles#index'
      get 'signup' => 'users#new'
      get '/login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'
      post 'articles' => 'articles#create'

      resources :articles
      resources :user

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.erb
<nav class="navbar navbar-custom" id="nav">
  <div class="container-fluid">
    <a class="navbar-brand navbar-left" id="brand" href="/">ChatMe</a>
    <div class="dropdown navbar-right">
      <button class="btn btn-custom dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span class="glyphicon glyphicon-align-justify"></span>
      </button>
      <ul class="dropdown-menu" id="menu" aria-labelledby="dropdownMenu1">
        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Profile</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-star"></i>Friends List</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>Messages</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-in"></i>Login</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-out"></i>Logout</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-pencil"></i>Register</a></li>
      </ul>
    </div>
  </div>
</nav>

<aside class="sidebar" id="sidebar">
  <article>
    <h3>Free Writing Is Beautiful</h3>
    <p>The art of writing has been around for centuries. Writing is the best way people can express themselves. You can
      writing with your emotions to free your mind from the situation or current events going on inside of your day to
      day life.</p>
  </article>
</aside>

<% @articles.each do |article| %>
    <div class="container article_area">
      <div class="col-sm-12 title">
      <h2 class="title"><%= article.title %></h2>
      </div>
      <div class="col-sm-12 body">
      <article class="content"><%= article.body %></article>
      </div>
      <div class="col-sm-12 time">
      <p class="time"><%= article.created_at %></p>
    </div>
    </div>
<% end %>

<%= button_to "Create an Article", new_article_path, :class => "create_article_link", :method => 'get' %>

app/views/articles/new.erb
<nav class="navbar navbar-custom" id="nav">
  <div class="container-fluid">
    <a class="navbar-brand navbar-left" id="brand" href="/">ChatMe</a>
    <div class="dropdown navbar-right">
      <button class="btn btn-custom dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span class="glyphicon glyphicon-align-justify"></span>
      </button>
      <ul class="dropdown-menu" id="menu" aria-labelledby="dropdownMenu1">
        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Profile</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-star"></i>Friends List</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>Messages</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-in"></i>Login</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-out"></i>Logout</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-pencil"></i>Register</a></li>
      </ul>
    </div>
  </div>
</nav>

<aside class="sidebar" id="sidebar">
  <article>
    <h3>Free Writing Is Beautiful</h3>
    <p>The art of writing has been around for centuries. Writing is the best way people can express themselves. You can
      writing with your emotions to free your mind from the situation or current events going on inside of your day to
      day life.</p>
  </article>
</aside>

<div class="create">
  <div class="container-fluid">


    <%= form_for @article do |t| %>
        <%= t.text_field :title, :placeholder => 'Title', :class => 'article_title'  %>
        <%= t.text_area :body, :placeholder => 'Article', :class => 'article_body' %>
        <%= t.submit 'Post', :class => 'btn-btn-article' %>
<% end %>
      </div>
    </div>  

app/views/home/home.erb
<nav class="navbar navbar-custom" id="nav">
  <div class="container-fluid">
   <%= link_to 'ChatMe', root_path, :class => 'navbar-brand navbar-left', :id => 'brand'%>
    <div class="dropdown navbar-right">
      <button class="btn btn-custom dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <span class="glyphicon glyphicon-align-justify"></span>
      </button>
      <ul class="dropdown-menu" id="menu" aria-labelledby="dropdownMenu1">
        <li><a href="#"><i class="glyphicon glyphicon-user"></i>Profile</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-star"></i>Friends List</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>Messages</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-in"></i>Login</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-log-out"></i>Logout</a></li>
        <li class="divider"></li>
        <li><a href="#"><i class="glyphicon glyphicon-pencil"></i>Register</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="jumbotron">
  <div class="container">
    <h1 class="mainheader">Welcome to ChatMe</h1>
    <p>ChatMe is a site for peer to peer communication with no hassle. Make an account and friend request your
    friends and family and begin freely conversing with them!</p>
  </div>
</div>

<aside class="sidebar" id="sidebar">
  <article>
    <h3>Free Writing Is Beautiful</h3>
    <p>The art of writing has been around for centuries. Writing is the best way people can express themselves. You can
    writing with your emotions to free your mind from the situation or current events going on inside of your day to
    day life.</p>
  </article>
</aside>

<div class="articles">
  <div class="container-fluid">

    <%= button_to "Create an Article", new_article_path, :class => "create_article_link", :method => 'get' %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatme</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/users/new.erb
<div class="login">
  <div class="container">
    <div class="form">

      <h1>Sign up</h1>

      <%= form_for(@users) do |t| %>
          <%= f.text_field :first_name, :placeholder => 'First name' %>
          <%= f.text_field :last_name, :placeholder => 'Last name' %>
          <%= f.email_field :email, :placeholder => 'Email' %>
          <%= f.password_field :password, :placeholder => 'Password' %>
          <%= f.submit 'Create an account', class: 'btn-submit' %>
      <% end %>


    </div>
  </div>
</div>